### ISSUE TITLE
Block Inbound

### ISSUE THREAD

**Issue by masterlord91** [asheroto/BlockFolderWindowsFirewall#1]
can add function to block inbound also> thank you.

**Comment by asheroto** [comment]
Thanks! I have updated the script. Check Releases for release notes and the readme for more information.

```powershell
Install-Script BlockFolderWindowsFirewall -Force
```

That will update it.

**Comment by masterlord91** [comment]
> Thanks! I have updated the script. Check Releases for release notes and the readme for more information.
> 
> ```powershell
> Install-Script BlockFolderWindowsFirewall -Force
> ```
> 
> That will update it.

awesome, thank you
