### ISSUE TITLE
The term x86 is not recognized

### ISSUE THREAD

**Issue by Atulin** [asheroto/BlockFolderWindowsFirewall#2]
```
> BlockFolderWindowsFirewall.ps1 -Path "C:/Program Files (x86)/Some Files/Folder" -Recurse
x86: The term 'x86' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by asheroto** [comment]
Hmm.. Not sure why this is happening. It's working for me...

![image](https://github.com/asheroto/BlockFolderWindowsFirewall/assets/49938263/662049ea-2558-485d-8c4a-f92c8c555810)

Tried it with both backslash and forward slash.

I tried it in PowerShell 5 and PowerShell 7 with the same result. Are you perhaps running the script in a manner that would modify the way the parameter values are interpreted?

I'm assuming you're using the latest version, right?

**Comment by Atulin** [comment]
Yes. Latest version, Powershell 7.4.1 in Windows Terminal. I did not call it from an elevated terminal, though, maybe that could be the issue.

**Comment by asheroto** [comment]
Yeah, I bet that's the reason. In the later versions of Windows, you generally have to `Run as Administrator` to work with files in `C:\Program Files`, `C:\Program Files (x86)` and `C:\Windows`.

I'm going to go ahead and close the ticket but if for some reason you find a bug let me know.
